CREATE TABLE [dbo].[CP_UserRole] (
    [UserID] INT NULL,
    [RoleID] INT NULL,
    CONSTRAINT [FK_T_USER_ROLE_T_ROLE] FOREIGN KEY ([RoleID]) REFERENCES [dbo].[CP_Role] ([ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_T_USER_ROLE_T_USER] FOREIGN KEY ([UserID]) REFERENCES [dbo].[CP_User] ([ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[CP_UserRole] NOCHECK CONSTRAINT [FK_T_USER_ROLE_T_ROLE];


GO
ALTER TABLE [dbo].[CP_UserRole] NOCHECK CONSTRAINT [FK_T_USER_ROLE_T_USER];

