CREATE TABLE [dbo].[MMO_Product] (
    [ID]                   INT             IDENTITY (1, 1) NOT NULL,
    [SKU]                  NVARCHAR (100)  NULL,
    [Name]                 NVARCHAR (500)  NULL,
    [DisplayName]          NVARCHAR (500)  NULL,
    [PageTitle]            NVARCHAR (200)  NULL,
    [PageDescription]      NVARCHAR (500)  NULL,
    [PageKeywords]         NVARCHAR (500)  NULL,
    [SalePrice]            DECIMAL (18, 2) NULL,
    [DiscountedPrice]      DECIMAL (18, 2) NULL,
    [DiscountedPercentage] INT             NULL,
    [DiscountedValue]      DECIMAL (18, 2) NULL,
    [CurrencyId]           INT             NULL,
    [Category_LV1]         NVARCHAR (200)  NULL,
    [Category_LV2]         NVARCHAR (200)  NULL,
    [Category_LV3]         NVARCHAR (200)  NULL,
    [Category_LV1_Id]      INT             NULL,
    [Category_LV2_Id]      INT             NULL,
    [Category_LV3_Id]      INT             NULL,
    [CategoryPath]         NVARCHAR (1024) NULL,
    [Image1]               NVARCHAR (1024) NULL,
    [Image2]               NVARCHAR (1024) NULL,
    [Image3]               NVARCHAR (1024) NULL,
    [Image4]               NVARCHAR (1024) NULL,
    [Image5]               NVARCHAR (1024) NULL,
    [Url]                  NVARCHAR (1024) NULL,
    [RedirectUrl]          NVARCHAR (2048) NULL,
    [Brand]                NVARCHAR (50)   NULL,
    [BrandId]              INT             NULL,
    [Status]               BIT             CONSTRAINT [DF_MMO_Product_Status] DEFAULT ((1)) NULL,
    [MenuID]               INT             NULL,
    [LangID]               INT             CONSTRAINT [DF_MMO_Product_LangID] DEFAULT ((1)) NULL,
    [UserId]               INT             CONSTRAINT [DF_MMO_Product_UserId] DEFAULT ((1)) NULL,
    [MarketplaceId]        INT             CONSTRAINT [DF_MMO_Product_MarketplaceId] DEFAULT ((1)) NULL,
    [CountClick]           INT             CONSTRAINT [DF_MMO_Product_CountClick] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_MMO_Product] PRIMARY KEY CLUSTERED ([ID] ASC)
);

